language: ruby

rvm:
  - "2.3"
  - "2.4"

env:
  global:
    -
      LC_ALL=en_US.UTF_8
      LANG=en_US.UTF_8

jobs:
  include:
    - script: bundle exec rake rubocop
      env: JOB=rubocop
      rvm: "2.4"

matrix:
  fast_finish: true
  include:
    - rvm: ruby-head
    - rvm: jruby-9.1.9.0
      env: DISABLE_NOKOGIRI=1
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.1.9.0
      env: DISABLE_NOKOGIRI=1

script:
  - bundle exec rake test

cache: bundler

sudo: false

git:
  depth: 10
